var sqldb = require('../../sqldb');
var Patient = sqldb.Patient;

Patient.sync()
  .then(function(){
    return Patient.destroy({where: {}});
  })
  .then(function(){
    Patient.bulkCreate([
      {
        title: 'Mr.',
        first_name: 'Charles',
        middle_name: 'D.',
        last_name: 'Parker',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'John',
        middle_name: 'U.',
        last_name: 'Stevens',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '2460 Langtown Road Farmersburg, IA 52047',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Richard',
        middle_name: 'C.',
        last_name: 'Aycock',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Michael',
        middle_name: 'T.',
        last_name: 'Turner',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Shirley',
        middle_name: 'C.',
        last_name: 'Jones',
        birthday: Date('November 7, 1964'),
        gender: 'Female',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Nathan',
        middle_name: 'D.',
        last_name: 'Stgeorge',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Donna',
        middle_name: 'A.',
        last_name: 'Marcotte',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Jacque',
        middle_name: 'R.',
        last_name: 'Garza',
        birthday: Date('November 7, 1964'),
        gender: 'Female',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Gale',
        middle_name: 'T.',
        last_name: 'Thomas',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Peggy',
        middle_name: 'F.',
        last_name: 'Humphries',
        birthday: Date('November 7, 1964'),
        gender: 'Female',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Eric',
        middle_name: 'A.',
        last_name: 'Mahon',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Ashley',
        middle_name: 'W.',
        last_name: 'Nelson',
        birthday: Date('November 7, 1964'),
        gender: 'Female',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Linda',
        middle_name: 'L.',
        last_name: 'Chin',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'John',
        middle_name: 'G.',
        last_name: 'Welch',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Carrie',
        middle_name: 'J.',
        last_name: 'Cooper',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Shawn',
        middle_name: 'M.',
        last_name: 'McCarley',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Alan',
        middle_name: 'R.',
        last_name: 'Hearn',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'James',
        middle_name: 'L.',
        last_name: 'Danielson',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'George',
        middle_name: 'L.',
        last_name: 'Hernandez',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Chris',
        middle_name: 'L.',
        last_name: 'Stallard',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Ronald',
        middle_name: 'L.',
        last_name: 'Saunders',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'David',
        middle_name: 'L.',
        last_name: 'Miller',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Su',
        middle_name: 'L.',
        last_name: 'Allen',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Irma',
        middle_name: 'L.',
        last_name: 'Davis',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'John',
        middle_name: 'L.',
        last_name: 'Tartt',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Julie',
        middle_name: 'L.',
        last_name: 'Kirk',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Christine',
        middle_name: 'L.',
        last_name: 'Osborne',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Daniel',
        middle_name: 'L.',
        last_name: 'Mengel',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Lizette',
        middle_name: 'L.',
        last_name: 'Fennell',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mrs.',
        first_name: 'Roxie',
        middle_name: 'L.',
        last_name: 'Roberts',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Dion',
        middle_name: 'B.',
        last_name: 'Song',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    },{
        title: 'Mr.',
        first_name: 'Monica',
        middle_name: 'L.',
        last_name: 'Russell',
        birthday: Date('November 7, 1964'),
        gender: 'Male',
        language: 'English',
        occupation: 'Electrical power line repairer',
        father_name: 'Dewitt',
        nationality: 'American',
        religion: 'Christianity',
        place_of_birth: 'Hendersonville',
        maritial_status: 'Single',
        sopouse_name: '',
        spouse_mobile: '',
        emergency_contact_name: 'Florence L. Powell',
        emergency_contact_mobile: '810-679-8170',
        emergency_contact_relation: 'friend',
        mobile: '615-826-6047',
        home_phone: '615-826-6047',
        work_phone: '615-826-6047',
        email: 'CharlesDParker@jourrapide.com',
        home_address: '1251 Buffalo Creek RoadHendersonville, TN 37075',
        home_street: 'Creek Road',
        home_city: 'Buffalo',
        insurance_company: 'Blue Shield',
        insurance_fund: 'Red Shield',
        insurance_fund_no: '759-01-XXXX',
        insurance_info: '1Z W27 551 34 2370 985 9',
        blood_type: 'A',
        blood_rh: '+',
        allergies: 'Penicillin',
        major_illness: 'diabides',
        additional_info: ''
    }
    ])
    .then(function(){
      console.log('finished populating Patients');
    });
  });