'use strict'
// Random name generator

var female_names =["Emma","Isabella","Emily","Madison","Ava","Olivia","Sophia","Abigail","Elizabeth","Chloe","Samantha","Addison","Natalie","Mia","Alexis","Alyssa","Hannah","Ashley","Ella","Sarah","Grace","Taylor","Brianna","Lily","Hailey","Anna","Victoria","Kayla","Lillian","Lauren","Kaylee","Allison","Savannah","Nevaeh","Gabriella","Sofia","Makayla","Avery","Riley","Julia","Leah","Aubrey","Jasmine","Audrey","Katherine","Morgan","Brooklyn","Destiny","Sydney","Alexa","Kylie","Brooke","Kaitlyn","Evelyn","Layla","Madeline","Kimberly","Zoe","Jessica","Peyton","Alexandra","Claire","Madelyn","Maria","Mackenzie","Arianna","Jocelyn","Amelia","Angelina","Trinity","Andrea","Maya","Valeria","Sophie","Rachel","Vanessa","Aaliyah","Mariah","Gabrielle","Katelyn","Ariana","Bailey","Camila","Jennifer","Melanie","Gianna","Charlotte","Paige","Autumn","Payton","Faith","Sara","Isabelle","Caroline","Genesis","Isabel","Mary","Zoey","Gracie","Megan","Haley","Mya","Michelle","Molly","Stephanie","Nicole","Jenna","Natalia","Sadie","Jada","Serenity","Lucy","Ruby","Eva","Kennedy","Rylee","Jayla","Naomi","Rebecca","Lydia","Daniela","Bella","Keira","Adriana","Lilly","Hayden","Miley","Katie","Jade","Jordan","Gabriela","Amy","Angela","Melissa","Valerie","Giselle","Diana","Amanda","Kate","Laila","Reagan","Jordyn","Kylee","Danielle","Briana","Marley","Leslie","Kendall","Catherine","Liliana","Mckenzie","Jacqueline","Ashlyn","Reese","Marissa","London","Juliana","Shelby","Cheyenne","Angel","Daisy","Makenzie","Miranda","Erin","Amber","Alana","Ellie","Breanna","Ana","Mikayla","Summer","Piper","Adrianna","Jillian","Sierra","Jayden","Sienna","Alicia","Lila","Margaret","Alivia","Brooklynn","Karen","Violet","Sabrina","Stella","Aniyah","Annabelle","Alexandria","Kathryn","Skylar","Aliyah","Delilah","Julianna","Kelsey","Khloe","Carly","Amaya","Mariana","Christina","Alondra","Tessa","Eliana","Bianca","Jazmin","Clara","Vivian","Josephine","Delaney","Scarlett","Elena","Cadence","Alexia","Maggie","Laura","Nora","Ariel","Elise","Nadia","Mckenna","Chelsea","Lyla","Alaina","Jasmin","Hope","Leila","Caitlyn","Cassidy","Makenna","Allie","Izabella","Eden","Callie","Haylee","Caitlin","Kendra","Karina","Kyra","Kayleigh","Addyson","Kiara","Jazmine","Karla","Camryn","Alina","Lola","Kyla","Kelly","Fatima","Tiffany","Kira","Crystal","Mallory","Esmeralda","Alejandra","Eleanor","Angelica","Jayda","Abby","Kara","Veronica","Carmen","Jamie","Ryleigh","Valentina","Allyson","Dakota","Kamryn","Courtney","Cecilia","Madeleine","Aniya","Alison","Esther","Heaven","Aubree","Lindsey","Leilani","Nina","Melody","Macy","Ashlynn","Joanna","Cassandra","Alayna","Kaydence","Madilyn","Aurora","Heidi","Emerson","Kimora","Madalyn","Erica","Josie","Katelynn","Guadalupe","Harper","Ivy","Lexi","Camille","Savanna","Dulce","Daniella","Lucia","Emely","Joselyn","Kiley","Kailey","Miriam","Cynthia","Rihanna","Georgia","Rylie","Harmony","Kiera","Kyleigh","Monica","Bethany","Kaylie","Cameron","Teagan","Cora","Brynn","Ciara","Genevieve","Alice","Maddison","Eliza","Tatiana","Jaelyn","Erika","Ximena","April","Marely","Julie","Danica","Presley","Brielle","Julissa","Angie","Iris","Brenda","Hazel","Rose","Malia","Shayla","Fiona","Phoebe","Nayeli","Paola","Kaelyn","Selena","Audrina","Rebekah","Carolina","Janiyah","Michaela","Penelope","Janiya","Anastasia","Adeline","Ruth","Sasha","Denise","Holly","Madisyn","Hanna","Tatum","Marlee","Nataly","Helen","Janelle","Lizbeth","Serena","Anya","Jaslene","Kaylin","Jazlyn","Nancy","Lindsay","Desiree","Hayley","Itzel","Imani","Madelynn","Asia","Kadence","Madyson","Talia","Jane","Kayden","Annie","Amari","Bridget","Raegan","Jadyn","Celeste","Jimena","Luna","Yasmin","Emilia","Annika","Estrella","Sarai","Lacey","Ayla","Alessandra","Willow","Nyla","Dayana","Lilah","Lilliana","Natasha","Hadley","Harley","Priscilla","Claudia","Allisson","Baylee","Brenna","Brittany","Skyler","Fernanda","Danna","Melany","Cali","Lia","Macie","Lyric","Logan","Gloria","Lana","Mylee","Cindy","Lilian","Amira","Anahi","Alissa","Anaya","Lena","Ainsley","Sandra","Noelle","Marisol","Meredith","Kailyn","Lesly","Johanna","Diamond","Evangeline","Juliet","Kathleen","Meghan","Paisley","Athena","Hailee","Rosa","Wendy","Emilee","Sage","Alanna","Elaina","Cara","Nia","Paris","Casey","Dana","Emery","Rowan","Aubrie","Kaitlin","Jaden","Kenzie","Kiana","Viviana","Norah","Lauryn","Perla","Amiyah","Alyson","Rachael","Shannon","Aileen","Miracle","Lillie","Danika","Heather","Kassidy","Taryn","Tori","Francesca","Kristen","Amya","Elle","Kristina","Cheyanne","Haylie","Patricia","Anne","Samara","Skye","Kali","America","Lexie","Parker","Halle","Londyn","Abbigail","Linda","Hallie","Saniya","Bryanna","Bailee","Jaylynn","Mckayla","Quinn","Jaelynn","Jaida","Caylee","Jaiden","Melina","Abril","Sidney","Kassandra","Elisabeth","Adalyn","Kaylynn","Mercedes","Yesenia","Elliana","Brylee","Dylan","Isabela","Ryan","Ashlee","Daphne","Kenya","Marina","Christine","Mikaela","Kaitlynn","Justice","Saniyah","Jaliyah","Ingrid","Marie","Natalee","Joy","Juliette","Simone","Adelaide","Krystal","Kennedi","Mila","Tamia","Addisyn","Aylin","Dayanara","Sylvia","Clarissa","Maritza","Virginia","Braelyn","Jolie","Jaidyn","Kinsley","Kirsten","Laney","Marilyn","Whitney","Janessa","Raquel","Anika","Kamila","Aria","Rubi","Adelyn","Amara","Ayanna","Teresa","Zariah","Kaleigh","Amani","Carla","Yareli","Gwendolyn","Paulina","Nathalie","Annabella","Jaylin","Tabitha","Deanna","Madalynn","Journey","Aiyana","Skyla","Yaretzi","Ada","Liana","Karlee","Jenny","Myla","Cristina","Myah","Lisa","Tania","Isis","Jayleen","Jordin","Arely","Azul","Helena","Aryanna","Jaqueline","Lucille","Destinee","Martha","Zoie","Arielle","Liberty","Marlene","Elisa","Isla","Noemi","Raven","Jessie","Aleah","Kailee","Kaliyah","Lilyana","Haven","Tara","Giana","Camilla","Maliyah","Irene","Carley","Maeve","Lea","Macey","Sharon","Alisha","Marisa","Jaylene","Kaya","Scarlet","Siena","Adyson","Maia","Shiloh","Tiana","Jaycee","Gisselle","Yazmin","Eve","Shyanne","Arabella","Sherlyn","Sariah","Amiya","Kiersten","Madilynn","Shania","Aleena","Finley","Kinley","Kaia","Aliya","Taliyah","Pamela","Yoselin","Ellen","Carlie","Monserrat","Jakayla","Reyna","Yaritza","Carolyn","Clare","Lorelei","Paula","Zaria","Gracelyn","Kasey","Regan","Alena","Angelique","Regina","Britney","Emilie","Mariam","Jaylee","Julianne","Greta","Elyse","Lainey","Kallie","Felicity","Zion","Aspen","Carlee","Annalise","Iliana","Larissa","Akira","Sonia","Catalina","Phoenix","Joslyn","Anabelle","Mollie","Susan","Judith","Destiney","Hillary","Janet","Katrina","Mareli","Ansley","Kaylyn","Alexus","Gia","Maci","Elsa","Stacy","Kaylen","Carissa","Haleigh","Lorena","Jazlynn","Milagros","Luz","Leanna","Renee","Shaniya","Charlie","Abbie","Cailyn","Cherish","Elsie","Jazmyn","Elaine","Emmalee","Luciana","Dahlia","Jamya","Belinda","Mariyah","Chaya","Dayami","Rhianna","Yadira","Aryana","Rosemary","Armani","Cecelia","Celia","Barbara","Cristal","Eileen","Rayna","Campbell","Amina","Aisha","Amirah","Ally","Araceli","Averie","Mayra","Sanaa","Patience","Leyla","Selah","Zara","Chanel","Kaiya","Keyla","Miah","Aimee","Giovanna","Amelie","Kelsie","Alisson","Angeline","Dominique","Adrienne","Brisa","Cierra","Paloma","Isabell","Precious","Alma","Charity","Jacquelyn","Janae","Frances","Shyla","Janiah","Kierra","Karlie","Annabel","Jacey","Karissa","Jaylah","Xiomara","Edith","Marianna","Damaris","Deborah","Jaylyn","Evelin","Mara","Olive","Ayana","India","Kendal","Kayley","Tamara","Briley","Charlee","Nylah","Abbey","Moriah","Saige","Savanah","Giada","Hana","Lizeth","Matilda","Ann","Jazlene","Gillian","Beatrice","Ireland","Karly","Mylie","Yasmine","Ashly","Kenna","Maleah","Corinne","Keely","Tanya","Tianna","Adalynn","Ryann","Salma","Areli","Karma","Shyann","Kaley","Theresa","Evie","Gina","Roselyn","Kaila","Jaylen","Natalya","Meadow","Rayne","Aliza","Yuliana","June","Lilianna","Nathaly","Ali","Alisa","Aracely","Belen","Tess","Jocelynn","Litzy","Makena","Abagail","Giuliana","Joyce","Libby","Lillianna","Thalia","Tia","Sarahi","Zaniyah","Kristin","Lorelai","Mattie","Taniya","Jaslyn","Gemma","Valery","Lailah","Mckinley","Micah","Deja","Frida","Brynlee","Jewel","Krista","Mira","Yamilet","Adison","Carina","Karli","Magdalena","Stephany","Charlize","Raelynn","Aliana","Cassie","Mina","Karley","Shirley","Marlie","Alani","Taniyah","Cloe","Sanai","Lina","Nola","Anabella","Dalia","Raina","Mariela","Ariella","Bria","Kamari","Monique","Ashleigh","Reina","Alia","Ashanti","Lara","Lilia","Justine","Leia","Maribel","Abigayle","Tiara","Alannah","Princess","Sydnee","Kamora","Paityn","Payten","Naima","Gretchen","Heidy","Nyasia","Livia","Marin","Shaylee","Maryjane","Laci","Nathalia","Azaria","Anabel","Chasity","Emmy","Izabelle","Denisse","Emelia","Mireya","Shea","Amiah","Dixie","Maren","Averi","Esperanza","Micaela","Selina","Alyvia","Chana","Avah","Donna","Kaylah","Ashtyn","Karsyn","Makaila","Shayna","Essence","Leticia","Miya","Rory","Desirae","Kianna","Laurel","Neveah","Amaris","Hadassah","Dania","Hailie","Jamiya","Kathy","Laylah","Riya","Diya","Carleigh","Iyana","Kenley","Sloane","Elianna"];

var male_names = ["Jacob","Michael","Ethan","Joshua","Daniel","Alexander","Anthony","William","Christopher","Matthew","Jayden","Andrew","Joseph","David","Noah","Aiden","James","Ryan","Logan","John","Nathan","Elijah","Christian","Gabriel","Benjamin","Jonathan","Tyler","Samuel","Nicholas","Gavin","Dylan","Jackson","Brandon","Caleb","Mason","Angel","Isaac","Evan","Jack","Kevin","Jose","Isaiah","Luke","Landon","Justin","Lucas","Zachary","Jordan","Robert","Aaron","Brayden","Thomas","Cameron","Hunter","Austin","Adrian","Connor","Owen","Aidan","Jason","Julian","Wyatt","Charles","Luis","Carter","Juan","Chase","Diego","Jeremiah","Brody","Xavier","Adam","Carlos","Sebastian","Liam","Hayden","Nathaniel","Henry","Jesus","Ian","Tristan","Bryan","Sean","Cole","Alex","Eric","Brian","Jaden","Carson","Blake","Ayden","Cooper","Dominic","Brady","Caden","Josiah","Kyle","Colton","Kaden","Eli","Miguel","Antonio","Parker","Steven","Alejandro","Riley","Richard","Timothy","Devin","Jesse","Victor","Jake","Joel","Colin","Kaleb","Bryce","Levi","Oliver","Oscar","Vincent","Ashton","Cody","Micah","Preston","Marcus","Max","Patrick","Seth","Jeremy","Peyton","Nolan","Ivan","Damian","Maxwell","Alan","Kenneth","Jonah","Jorge","Mark","Giovanni","Eduardo","Grant","Collin","Gage","Omar","Emmanuel","Trevor","Edward","Ricardo","Cristian","Nicolas","Kayden","George","Jaxon","Paul","Braden","Elias","Andres","Derek","Garrett","Tanner","Malachi","Conner","Fernando","Cesar","Javier","Miles","Jaiden","Alexis","Leonardo","Santiago","Francisco","Cayden","Shane","Edwin","Hudson","Travis","Bryson","Erick","Jace","Hector","Josue","Peter","Jaylen","Mario","Manuel","Abraham","Grayson","Damien","Kaiden","Spencer","Stephen","Edgar","Wesley","Shawn","Trenton","Jared","Jeffrey","Landen","Johnathan","Bradley","Braxton","Ryder","Camden","Roman","Asher","Brendan","Maddox","Sergio","Israel","Andy","Lincoln","Erik","Donovan","Raymond","Avery","Rylan","Dalton","Harrison","Andre","Martin","Keegan","Marco","Jude","Sawyer","Dakota","Leo","Calvin","Kai","Drake","Troy","Zion","Clayton","Roberto","Zane","Gregory","Tucker","Rafael","Kingston","Dominick","Ezekiel","Griffin","Devon","Drew","Lukas","Johnny","Ty","Pedro","Tyson","Caiden","Mateo","Braylon","Cash","Aden","Chance","Taylor","Marcos","Maximus","Ruben","Emanuel","Simon","Corbin","Brennan","Dillon","Skyler","Myles","Xander","Jaxson","Dawson","Kameron","Kyler","Axel","Colby","Jonas","Joaquin","Payton","Brock","Frank","Enrique","Quinn","Emilio","Malik","Grady","Angelo","Julio","Derrick","Raul","Fabian","Corey","Gerardo","Dante","Ezra","Armando","Allen","Theodore","Gael","Amir","Zander","Adan","Maximilian","Randy","Easton","Dustin","Luca","Phillip","Julius","Charlie","Ronald","Jakob","Cade","Brett","Trent","Silas","Keith","Emiliano","Trey","Jalen","Darius","Lane","Jerry","Jaime","Scott","Graham","Weston","Braydon","Anderson","Rodrigo","Pablo","Saul","Danny","Donald","Elliot","Brayan","Dallas","Lorenzo","Casey","Mitchell","Alberto","Tristen","Rowan","Jayson","Gustavo","Aaden","Amari","Dean","Braeden","Declan","Chris","Ismael","Dane","Louis","Arturo","Brenden","Felix","Jimmy","Cohen","Tony","Holden","Reid","Abel","Bennett","Zackary","Arthur","Nehemiah","Ricky","Esteban","Cruz","Finn","Mauricio","Dennis","Keaton","Albert","Marvin","Mathew","Larry","Moises","Issac","Philip","Quentin","Curtis","Greyson","Jameson","Everett","Jayce","Darren","Elliott","Uriel","Alfredo","Hugo","Alec","Jamari","Marshall","Walter","Judah","Jay","Lance","Beau","Ali","Landyn","Yahir","Phoenix","Nickolas","Kobe","Bryant","Maurice","Russell","Leland","Colten","Reed","Davis","Joe","Ernesto","Desmond","Kade","Reece","Morgan","Ramon","Rocco","Orlando","Ryker","Brodie","Paxton","Jacoby","Douglas","Kristopher","Gary","Lawrence","Izaiah","Solomon","Nikolas","Mekhi","Justice","Tate","Jaydon","Salvador","Shaun","Alvin","Eddie","Kane","Davion","Zachariah","Dorian","Titus","Kellen","Camron","Isiah","Javon","Nasir","Milo","Johan","Byron","Jasper","Jonathon","Chad","Marc","Kelvin","Chandler","Sam","Cory","Deandre","River","Reese","Roger","Quinton","Talon","Romeo","Franklin","Noel","Alijah","Guillermo","Gunner","Damon","Jadon","Emerson","Micheal","Bruce","Terry","Kolton","Melvin","Beckett","Porter","August","Brycen","Dayton","Jamarion","Leonel","Karson","Zayden","Keagan","Carl","Khalil","Cristopher","Nelson","Braiden","Moses","Isaias","Roy","Triston","Walker","Kale","Jermaine","Leon","Rodney","Kristian","Mohamed","Ronan","Pierce","Trace","Warren","Jeffery","Maverick","Cyrus","Quincy","Nathanael","Skylar","Tommy","Conor","Noe","Ezequiel","Demetrius","Jaylin","Kendrick","Frederick","Terrance","Bobby","Jamison","Jon","Rohan","Jett","Kieran","Tobias","Ari","Colt","Gideon","Felipe","Kenny","Wilson","Orion","Kamari","Gunnar","Jessie","Alonzo","Gianni","Omari","Waylon","Malcolm","Emmett","Abram","Julien","London","Tomas","Allan","Terrell","Matteo","Tristin","Jairo","Reginald","Brent","Ahmad","Yandel","Rene","Willie","Boston","Billy","Marlon","Trevon","Aydan","Jamal","Aldo","Ariel","Cason","Braylen","Javion","Joey","Rogelio","Ahmed","Dominik","Brendon","Toby","Kody","Marquis","Ulises","Armani","Adriel","Alfonso","Branden","Will","Craig","Ibrahim","Osvaldo","Wade","Harley","Steve","Davin","Deshawn","Kason","Damion","Jaylon","Jefferson","Aron","Brooks","Darian","Gerald","Rolando","Terrence","Enzo","Kian","Ryland","Barrett","Jaeden","Ben","Bradyn","Giovani","Blaine","Madden","Jerome","Muhammad","Ronnie","Layne","Kolby","Leonard","Vicente","Cale","Alessandro","Zachery","Gavyn","Aydin","Xzavier","Malakai","Raphael","Cannon","Rudy","Asa","Darrell","Giancarlo","Elisha","Junior","Zackery","Alvaro","Lewis","Valentin","Deacon","Jase","Harry","Kendall","Rashad","Finnegan","Mohammed","Ramiro","Cedric","Brennen","Santino","Stanley","Tyrone","Chace","Francis","Johnathon","Teagan","Zechariah","Alonso","Kaeden","Kamden","Gilberto","Ray","Karter","Luciano","Nico","Kole","Aryan","Draven","Jamie","Misael","Lee","Alexzander","Camren","Giovanny","Amare","Rhett","Rhys","Rodolfo","Nash","Markus","Deven","Mohammad","Moshe","Quintin","Dwayne","Memphis","Atticus","Davian","Eugene","Jax","Antoine","Wayne","Randall","Semaj","Uriah","Clark","Aidyn","Jorden","Maxim","Aditya","Lawson","Messiah","Korbin","Sullivan","Freddy","Demarcus","Neil","Brice","King","Davon","Elvis","Ace","Dexter","Heath","Duncan","Jamar","Sincere","Irvin","Remington","Kadin","Soren","Tyree","Damarion","Talan","Adrien","Gilbert","Keenan","Darnell","Adolfo","Tristian","Derick","Isai","Rylee","Gauge","Harold","Kareem","Deangelo","Agustin","Coleman","Zavier","Lamar","Emery","Jaydin","Devan","Jordyn","Mathias","Prince","Sage","Seamus","Jasiah","Efrain","Darryl","Arjun","Mike","Roland","Conrad","Kamron","Hamza","Santos","Frankie","Dominique","Marley","Vance","Dax","Jamir","Kylan","Todd","Maximo","Jabari","Matthias","Haiden","Luka","Marcelo","Keon","Layton","Tyrell","Kash","Raiden","Cullen","Donte","Jovani","Cordell","Kasen","Rory","Alfred","Darwin","Ernest","Bailey","Gaige","Hassan","Jamarcus","Killian","Augustus","Trevin","Zain","Ellis","Rex","Yusuf","Bruno","Jaidyn","Justus","Ronin","Humberto","Jaquan","Josh","Kasey","Winston","Dashawn","Lucian","Matias","Sidney","Ignacio","Nigel","Van","Elian","Finley","Jaron","Addison","Aedan","Braedon","Jadyn","Konner","Zayne","Franco","Niko","Savion","Cristofer","Deon","Krish","Anton","Brogan","Cael","Coby","Kymani","Marcel","Yair","Dale","Bo","Jordon","Samir","Darien","Zaire","Ross","Vaughn","Devyn","Kenyon","Clay","Dario","Ishaan","Jair","Kael","Adonis","Jovanny","Clinton","Rey","Chaim","German","Harper","Nathen","Rigoberto","Sonny","Glenn","Octavio","Blaze","Keshawn","Ralph","Ean","Nikhil","Rayan","Sterling","Branson","Jadiel","Dillan","Jeramiah","Koen","Konnor","Antwan","Houston","Tyrese","Dereon","Leonidas","Zack","Fisher","Jaydan","Quinten","Nick","Urijah","Darion","Jovan","Salvatore","Beckham","Jarrett","Antony","Eden","Makai","Zaiden","Broderick","Camryn","Malaki","Nikolai","Howard","Immanuel","Demarion","Valentino","Jovanni","Ayaan","Ethen","Leandro","Royce","Yael","Yosef","Jean","Marquise","Alden","Leroy","Gaven","Jovany","Tyshawn","Aarav","Kadyn","Milton","Zaid","Kelton","Tripp","Kamren","Slade","Hezekiah","Jakobe","Nathanial","Rishi","Shamar","Geovanni","Pranav","Roderick","Bentley","Clarence","Lyric","Bernard","Carmelo","Denzel","Maximillian","Reynaldo","Cassius","Gordon","Reuben","Samson","Yadiel","Jayvon","Reilly","Sheldon","Abdullah","Jagger","Thaddeus","Case","Kyson","Lamont","Chaz","Makhi","Jan","Marques","Oswaldo","Donavan","Keyon","Kyan","Simeon","Trystan","Andreas","Dangelo","Landin","Reagan","Turner","Arnav","Brenton","Callum","Jayvion","Bridger","Sammy","Deegan","Jaylan","Lennon","Odin","Abdiel","Jerimiah","Eliezer","Bronson","Cornelius","Pierre","Cortez","Baron","Carlo","Carsen","Fletcher","Izayah","Kolten","Damari","Hugh","Jensen","Yurem"];

var last_names = ["Smith","Johnson","Williams","Brown","Jones","Miller","Davis","Garcia","Rodriguez","Wilson","Martinez","Anderson","Taylor","Thomas","Hernandez","Moore","Martin","Jackson","Thompson","White","Lopez","Lee","Gonzalez","Harris","Clark","Lewis","Robinson","Walker","Perez","Hall","Young","Allen","Sanchez","Wright","King","Scott","Green","Baker","Adams","Nelson","Hill","Ramirez","Campbell","Mitchell","Roberts","Carter","Phillips","Evans","Turner","Torres","Parker","Collins","Edwards","Stewart","Flores","Morris","Nguyen","Murphy","Rivera","Cook","Rogers","Morgan","Peterson","Cooper","Reed","Bailey","Bell","Gomez","Kelly","Howard","Ward","Cox","Diaz","Richardson","Wood","Watson","Brooks","Bennett","Gray","James","Reyes","Cruz","Hughes","Price","Myers","Long","Foster","Sanders","Ross","Morales","Powell","Sullivan","Russell","Ortiz","Jenkins","Gutierrez","Perry","Butler","Barnes","Fisher","Henderson","Coleman","Simmons","Patterson","Jordan","Reynolds","Hamilton","Graham","Kim","Gonzales","Alexander","Ramos","Wallace","Griffin","West","Cole","Hayes","Chavez","Gibson","Bryant","Ellis","Stevens","Murray","Ford","Marshall","Owens","Mcdonald","Harrison","Ruiz","Kennedy","Wells","Alvarez","Woods","Mendoza","Castillo","Olson","Webb","Washington","Tucker","Freeman","Burns","Henry","Vasquez","Snyder","Simpson","Crawford","Jimenez","Porter","Mason","Shaw","Gordon","Wagner","Hunter","Romero","Hicks","Dixon","Hunt","Palmer","Robertson","Black","Holmes","Stone","Meyer","Boyd","Mills","Warren","Fox","Rose","Rice","Moreno","Schmidt","Patel","Ferguson","Nichols","Herrera","Medina","Ryan","Fernandez","Weaver","Daniels","Stephens","Gardner","Payne","Kelley","Dunn","Pierce","Arnold","Tran","Spencer","Peters","Hawkins","Grant","Hansen","Castro","Hoffman","Hart","Elliott","Cunningham","Knight","Bradley","Carroll","Hudson","Duncan","Armstrong","Berry","Andrews","Johnston","Ray","Lane","Riley","Carpenter","Perkins","Aguilar","Silva","Richards","Willis","Matthews","Chapman","Lawrence","Garza","Vargas","Watkins","Wheeler","Larson","Carlson","Harper","George","Greene","Burke","Guzman","Morrison","Munoz","Jacobs","Obrien","Lawson","Franklin","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Dean","Hanson","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Guerrero","Stanley","Bates","Alvarado","Beck","Ortega","Wade","Estrada","Contreras","Barnett","Caldwell","Santiago","Lambert","Powers","Chambers","Nunez","Craig","Leonard","Lowe","Rhodes","Byrd","Gregory","Shelton","Frazier","Becker","Maldonado","Fleming","Vega","Sutton","Cohen","Jennings","Parks","Mcdaniel","Watts","Barker","Norris","Vaughn","Vazquez","Holt","Schwartz","Steele","Benson","Neal","Dominguez","Horton","Terry","Wolfe","Hale","Lyons","Graves","Haynes","Miles","Park","Warner","Padilla","Bush","Thornton","Mccarthy","Mann","Zimmerman","Erickson","Fletcher","Mckinney","Page","Dawson","Joseph","Marquez","Reeves","Klein","Espinoza","Baldwin","Moran","Love","Robbins","Higgins","Ball","Cortez","Le","Griffith","Bowen","Sharp","Cummings","Ramsey","Hardy","Swanson","Barber","Acosta","Luna","Chandler","Blair","Daniel","Cross","Simon","Dennis","Oconnor","Quinn","Gross","Navarro","Moss","Fitzgerald","Doyle","Mclaughlin","Rojas","Rodgers","Stevenson","Singh","Yang","Figueroa","Harmon","Newton","Paul","Manning","Garner","Mcgee","Reese","Francis","Burgess","Adkins","Goodman","Curry","Brady","Christensen","Potter","Walton","Goodwin","Mullins","Molina","Webster","Fischer","Campos","Avila","Sherman","Todd","Chang","Blake","Malone","Wolf","Hodges","Juarez","Gill","Farmer","Hines","Gallagher","Duran","Hubbard","Cannon","Miranda","Wang","Saunders","Tate","Mack","Hammond","Carrillo","Townsend","Wise","Ingram","Barton","Mejia","Ayala","Schroeder","Hampton","Rowe","Parsons","Frank","Waters","Strickland","Osborne","Maxwell","Chan","Deleon","Norman","Harrington","Casey","Patton","Logan","Bowers","Mueller","Glover","Floyd","Hartman","Buchanan","Cobb","French","Kramer","Mccormick","Clarke","Tyler","Gibbs","Moody","Conner","Sparks","Mcguire","Leon","Bauer","Norton","Pope","Flynn","Hogan","Robles","Salinas","Yates","Lindsey","Lloyd","Marsh","Mcbride","Owen","Solis","Pham","Lang","Pratt","Lara","Brock","Ballard","Trujillo","Shaffer","Drake","Roman","Aguirre","Morton","Stokes","Lamb","Pacheco","Patrick","Cochran","Shepherd","Cain","Burnett","Hess","Li","Cervantes","Olsen","Briggs","Ochoa","Cabrera","Velasquez","Montoya","Roth","Meyers","Cardenas","Fuentes","Weiss","Hoover","Wilkins","Nicholson","Underwood","Short","Carson","Morrow","Colon","Holloway","Summers","Bryan","Petersen","Mckenzie","Serrano","Wilcox","Carey","Clayton","Poole","Calderon","Gallegos","Greer","Rivas","Guerra","Decker","Collier","Wall","Whitaker","Bass","Flowers","Davenport","Conley","Houston","Huff","Copeland","Hood","Monroe","Massey","Roberson","Combs","Franco","Larsen","Pittman","Randall","Skinner","Wilkinson","Kirby","Cameron","Bridges","Anthony","Richard","Kirk","Bruce","Singleton","Mathis","Bradford","Boone","Abbott","Charles","Allison","Sweeney","Atkinson","Horn","Jefferson","Rosales","York","Christian","Phelps","Farrell","Castaneda","Nash","Dickerson","Bond","Wyatt","Foley","Chase","Gates","Vincent","Mathews","Hodge","Garrison","Trevino","Villarreal","Heath","Dalton","Valencia","Callahan","Hensley","Atkins","Huffman","Roy","Boyer","Shields","Lin","Hancock","Grimes","Glenn","Cline","Delacruz","Camacho","Dillon","Parrish","Oneill","Melton","Booth","Kane","Berg","Harrell","Pitts","Savage","Wiggins","Brennan","Salas","Marks","Russo","Sawyer","Baxter","Golden","Hutchinson","Liu","Walter","Mcdowell","Wiley","Rich","Humphrey","Johns","Koch","Suarez","Hobbs","Beard","Gilmore","Ibarra","Keith","Macias","Khan","Andrade","Ware","Stephenson","Henson","Wilkerson","Dyer","Mcclure","Blackwell","Mercado","Tanner","Eaton","Clay","Barron","Beasley","Oneal","Preston","Small","Wu","Zamora","Macdonald","Vance","Snow","Mcclain","Stafford","Orozco","Barry","English","Shannon","Kline","Jacobson","Woodard","Huang","Kemp","Mosley","Prince","Merritt","Hurst","Villanueva","Roach","Nolan","Lam","Yoder","Mccullough","Lester","Santana","Valenzuela","Winters","Barrera","Leach","Orr","Berger","Mckee","Strong","Conway","Stein","Whitehead","Bullock","Escobar","Knox","Meadows","Solomon","Velez","Odonnell","Kerr","Stout","Blankenship","Browning","Kent","Lozano","Bartlett","Pruitt","Buck","Barr","Gaines","Durham","Gentry","Mcintyre","Sloan","Melendez","Rocha","Herman","Sexton","Moon","Hendricks","Rangel","Stark","Lowery","Hardin","Hull","Sellers","Ellison","Calhoun","Gillespie","Mora","Knapp","Mccall","Morse","Dorsey","Weeks","Nielsen","Livingston","Leblanc","Mclean","Bradshaw","Glass","Middleton","Buckley","Schaefer","Frost","Howe","House","Mcintosh","Ho","Pennington","Reilly","Hebert","Mcfarland","Hickman","Noble","Spears","Conrad","Arias","Galvan","Velazquez","Huynh","Frederick","Randolph","Cantu","Fitzpatrick","Mahoney","Peck","Villa","Michael","Donovan","Mcconnell","Walls","Boyle","Mayer","Zuniga","Giles","Pineda","Pace","Hurley","Mays","Mcmillan","Crosby","Ayers","Case","Bentley","Shepard","Everett","Pugh","David","Mcmahon","Dunlap","Bender","Hahn","Harding","Acevedo","Raymond","Blackburn","Duffy","Landry","Dougherty","Bautista","Shah","Potts","Arroyo","Valentine","Meza","Gould","Vaughan","Fry","Rush","Avery","Herring","Dodson","Clements","Sampson","Tapia","Bean","Lynn","Crane","Farley","Cisneros","Benton","Ashley","Mckay","Finley","Best","Blevins","Friedman","Moses","Sosa","Blanchard","Huber","Frye","Krueger","Bernard","Rosario","Rubio","Mullen","Benjamin","Haley","Chung","Moyer","Choi","Horne","Yu","Woodward","Ali","Nixon","Hayden","Rivers","Estes","Mccarty","Richmond","Stuart","Maynard","Brandt","Oconnell","Hanna","Sanford","Sheppard","Church","Burch","Levy","Rasmussen","Coffey","Ponce","Faulkner","Donaldson","Schmitt","Novak","Costa","Montes","Booker","Cordova","Waller","Arellano","Maddox","Mata","Bonilla","Stanton","Compton","Kaufman","Dudley","Mcpherson","Beltran","Dickson","Mccann","Villegas","Proctor","Hester","Cantrell","Daugherty","Cherry","Bray","Davila","Rowland","Levine","Madden","Spence","Good","Irwin","Werner","Krause","Petty","Whitney","Baird","Hooper","Pollard","Zavala","Jarvis","Holden","Haas","Hendrix","Mcgrath","Bird","Lucero","Terrell","Riggs","Joyce","Mercer","Rollins","Galloway","Duke","Odom","Andersen","Downs","Hatfield","Benitez","Archer","Huerta","Travis","Mcneil","Hinton","Zhang","Hays","Mayo","Fritz","Branch","Mooney","Ewing","Ritter","Esparza","Frey","Braun","Gay","Riddle","Haney","Kaiser","Holder","Chaney","Mcknight","Gamble","Vang","Cooley","Carney","Cowan","Forbes","Ferrell","Davies","Barajas","Shea","Osborn","Bright","Cuevas","Bolton","Murillo","Lutz","Duarte","Kidd","Key","Cooke"];

var occupations = [
"Able Seamen",
"Account Collector",
"Accounting Specialist",
"Adjustment Clerk",
"Administrative Assistant",
"Administrative Law Judge",
"Administrative Service Manager",
"Admiralty Lawyer",
"Adult Literacy and Remedial Education Teachers",
"Advertising Account Executive",
"Advertising Agency Coordinator",
"Aeronautical & Aerospace Engineer",
"Aerospace Engineering Technician",
"Agricultural Crop Farm Manager",
"Agricultural Engineer",
"Agricultural Equipment Operator",
"Agricultural Inspector",
"Agricultural Product Sorter",
"Agricultural Sciences Professor",
"Agricultural Technician",
"Air Crew Member",
"Air Crew Officer",
"Air Traffic Controller",
"Aircraft Assembler",
"Aircraft Body and Bonded Structure Repairer",
"Aircraft Cargo Handling Supervisor",
"Aircraft Examiner",
"Aircraft Launch and Recovery Officer",
"Aircraft Launch and Recovery Specialist",
"Aircraft Mechanic",
"Airfield Operations Specialist",
"Airline Flight Attendant",
"Airline Flight Control Administrator",
"Airline Flight Operations Administrator",
"Airline Flight Reservations Administrator",
"Airport Administrator",
"Airport Design Engineer",
"Alcohol & Drug Abuse Assistance Coordinator",
"Alumni Relations Coordinator",
"Ambulance Drivers",
"Amusement Park & Recreation Attendants",
"Anesthesiologist (MD)",
"Animal Breeder",
"Animal Control Worker",
"Animal Husbandry Worker Supervisor",
"Animal Keepers and Groomers",
"Animal Kennel Supervisor",
"Animal Scientist",
"Animal Trainer",
"Animation Cartoonist",
"Answering Service Operator",
"Anthropology and Archeology Professor",
"Anti-Terrorism Intelligence Agent",
"Appeals Referee",
"Aquaculturist (Fish Farmer)",
"Aquarium Curator",
"Architecture Professor",
"Area, Ethnic, and Cultural Studies Professor",
"Armored Assault Vehicle Crew Member",
"Armored Assault Vehicle Officer",
"Art Appraiser",
"Art Director",
"Art Restorer",
"Art Therapist",
"Art, Drama, and Music Professor",
"Artillery and Missile Crew Member",
"Artillery and Missile Officer",
"Artists Agent (Manager)",
"Athletes' Business Manager",
"Athletic Coach",
"Athletic Director",
"Athletic Trainer",
"ATM Machine Servicer",
"Atmospheric and Space Scientist",
"Audio-Visual Collections Specialist",
"Audiovisual Production Specialist",
"Automobile Mechanic",
"Automotive Body Repairer",
"Automotive Engineer",
"Automotive Glass Installer",
"Avionics Technician",
"Baggage Porters and Bellhops",
"Baker (Commercial)",
"Ballistics Expert",
"Bank and Branch Managers",
"Bank Examiner",
"Bank Teller",
"Benefits Manager",
"Bicycle Mechanic",
"Billing Specialist",
"Bindery Machine Set-Up Operators",
"Bindery Machine Tender",
"Biological Technician",
"Biology Professor",
"Biomedical Engineer",
"Biomedical Equipment Technician",
"Boat Builder",
"Book Editor",
"Border Patrol Agent",
"Brattice Builder",
"Bridge and Lock Tenders",
"Broadcast News Analyst",
"Broadcast Technician",
"Broker's Floor Representative",
"Brokerage Clerk",
"Budget Accountant",
"Budget Analyst",
"Building Inspector",
"Building Maintenance Mechanic",
"Bulldozer / Grader Operator",
"Bus and Truck Mechanics",
"Bus Boy / Bus Girl",
"Bus Driver (School)",
"Bus Driver (Transit)",
"Business Professor",
"Business Service Specialist",
"Cabinet Maker",
"Camp Director",
"Caption Writer",
"Cardiologist (MD)",
"Cardiopulmonary Technologist",
"Career Counselor",
"Cargo and Freight Agents",
"Carpenter's Assistant",
"Carpet Installer",
"Cartographer (Map Scientist)",
"Cartographic Technician",
"Cartoonist (Publications)",
"Casino Cage Worker",
"Casino Cashier",
"Casino Dealer",
"Casino Floor Person",
"Casino Manager",
"Casino Pit Boss",
"Casino Slot Machine Mechanic",
"Casino Surveillance Officer",
"Casting Director",
"Catering Administrator",
"Ceiling Tile Installer",
"Cement Mason",
"Ceramic Engineer",
"Certified Public Accountant (CPA)",
"Chaplain (Prison, Military, Hospital)",
"Chemical Engineer",
"Chemical Equipment Operator",
"Chemical Plant Operator",
"Chemical Technicians",
"Chemistry Professor",
"Chief Financial Officer",
"Child Care Center Administrator",
"Child Care Worker",
"Child Life Specialist",
"Child Support Investigator",
"Child Support Services Worker",
"City Planning Aide",
"Civil Drafter",
"Civil Engineer",
"Civil Engineering Technician",
"Clergy Member (Religious Leader)",
"Clinical Dietitian",
"Clinical Psychologist",
"Clinical Sociologist",
"Coatroom and Dressing Room Attendants",
"College/University Professor",
"Commercial Designer",
"Commercial Diver",
"Commercial Fisherman",
"Communication Equipment Mechanic",
"Communications Professor",
"Community Health Nurse",
"Community Organization Worker",
"Community Welfare Worker",
"Compensation Administrator",
"Compensation Specialist",
"Compliance Officer",
"Computer Aided Design (CAD) Technician",
"Computer and Information Scientists, Research",
"Computer and Information Systems Managers",
"Computer Applications Engineer",
"Computer Controlled Machine Tool Operators",
"Computer Customer Support Specialist",
"Computer Hardware Technician",
"Computer Operators",
"Computer Programmer",
"Computer Science Professor",
"Computer Security Specialist",
"Computer Software Engineers",
"Computer Software Technician",
"Computer Systems Engineer",
"Congressional Aide",
"Conservation Scientist",
"Construction Driller",
"Construction Laborer",
"Construction Manager",
"Construction Trades Supervisor",
"Contract Administrator",
"Contract Specialist",
"Control Center Specialist (Military)",
"Controller (Finance)",
"Cook (Cafeteria)",
"Cook (Fast Food)",
"Cook (Private Household)",
"Cook (Restaurant)",
"Cook (Short Order)",
"Copy Writer",
"Corporation Lawyer",
"Correction Officer",
"Correspondence Clerk",
"Cosmetologist (Hair Stylist)",
"Cost Accountant",
"Cost Analysis Engineer",
"Cost Estimator",
"Costume Attendant",
"Counseling Psychologist",
"Counter and Rental Clerks",
"County or City Auditor",
"Couriers and Messengers",
"Court Administrator",
"Court Clerk",
"Court Reporter",
"Craft Artist",
"Crane Operator",
"Credit Adjuster",
"Credit Analyst",
"Credit Reporter",
"Criminal Investigator (Detective)",
"Criminal Justice Professor",
"Criminal Lawyer",
"Crop Workers Supervisor",
"Crossing Guard",
"Custom Tailor",
"Customer Service Representative (Utilities)",
"Customer Service Supervisor",
"Customs Inspector",
"Cutting Machine Operators",
"Dairy Technologist",
"Database Administrator",
"Deaf Students Teacher",
"Delivery Driver",
"Demonstrators and Product Promoters",
"Dental / Orthodontic Office Administrator",
"Dental Assistant",
"Dental Hygienist",
"Dental Laboratory Technician",
"Dentist (MD)",
"Dermatologist (MD)",
"Desktop Publishing Specialist",
"Developmental Psychologist",
"Die Cutter Operator",
"Dietetic Technician",
"Dietitian and Nutritionist",
"Directory Assistance Operator",
"Disabled Students Teacher",
"Disk Jockey",
"Dispatcher (Safety Vehicles)",
"Door To Door Salesmen",
"Dry Wall Installer",
"Economics Professor",
"Editorial Writer, Newspapers & Magazines",
"Education and Training Administrator",
"Education Professor",
"Educational Administrator",
"Educational Psychologist",
"Educational Resource Coordinator",
"Educational Therapist",
"EEG Technician/Technologist",
"Electric Meter Installer",
"Electric Motor Mechanic",
"Electrical and Electronic Inspector",
"Electrical Drafter",
"Electrical Engineers",
"Electrical Parts Reconditioner",
"Electrical Technician",
"Electro-Mechanical Technicians",
"Electromechanical Equipment Assembler",
"Electronic Drafter",
"Electronics Engineer",
"Electronics Technician",
"Elementary School Administrator",
"Elementary School Teacher",
"Elevator Mechanic",
"Emergency Management Specialist",
"Emergency Medical Technician",
"Employee Benefits Analyst",
"Employee Training Instructor",
"Employment Administrator",
"Employment and Placement Specialist",
"Employment Interviewer",
"Engine and Machine Assemblers",
"Engineering Managers",
"Engineering Professor",
"English Language and Literature Professor",
"Environmental Compliance Inspector",
"Environmental Disease Analyst",
"Environmental Engineer",
"Environmental Planner",
"Environmental Research Analyst",
"Environmental Science Technician",
"Environmental Science Professsor",
"Environmental Technician",
"Equal Opportunity Representative",
"Etchers and Engravers",
"Excavating Machine Operator",
"Excavating Supervisor",
"Executive Secretary",
"Exercise Physiologist",
"Exhibit Artist",
"Exhibit Designer",
"Experimental Psychologist",
"Explosives Worker",
"Export Agent",
"Fabric and Apparel Patternmakers",
"Facilities Planner",
"Factory Layout Engineer",
"Family Caseworker",
"Family Practitioner (MD)",
"Farm Equipment Mechanic",
"Farm Hand",
"Farm Labor Contractor",
"Farm Manager",
"Farm Products Purchasing Agent",
"Farmers and Ranchers",
"Fashion Artist",
"Fashion Coordinator",
"Fashion Designer",
"Fashion Model",
"Fence Installer",
"Field Contractor",
"Field Health Officer",
"File Clerk",
"Film Editor",
"Film Laboratory Technician",
"Finance Manager",
"Financial Aid Counselor",
"Financial Analyst",
"Financial Examiner",
"Financial Planner",
"Financial Services Sales Agent",
"Fine Artist",
"Fire Inspector",
"Fire Investigator",
"Fire Prevention Engineer",
"Fire Protection Engineer",
"Fire Protection Engineering Technician",
"Fish & Game Warden",
"Fish Hatchery Specialist",
"Fishery Worker Supervisor",
"Fitness Trainer",
"Flight Engineers",
"Floral Designer",
"Food & Drug Inspector",
"Food Batchmaker",
"Food Preparation Worker",
"Food Science Technicians",
"Food Technologist",
"Foreign Exchange Trader",
"Foreign Language Interpreter",
"Foreign Language Teacher",
"Foreign Language Translator",
"Foreign Service Officer",
"Foreign Service Peacekeeping Specialist",
"Foreign Student Adviser",
"Forensic Science Technicians",
"Forensics Psychologist",
"Forest and Conservation Technician",
"Forest Engineer",
"Forest Fire Prevention Supervisor",
"Forest Fire Inspector",
"Forestry and Conservation Professor",
"Forging Machine Operator",
"Forklift and Industrial Truck Operators",
"Fraud Investigator",
"Freight and Stock Handler",
"Fund Raiser",
"Funds Development Administrator",
"Funeral Attendant",
"Funeral Director",
"Furniture Designer",
"Furniture Finishers",
"Game Runner",
"Gas Plant Operator",
"General and Operations Managers",
"General Farmworkers",
"General Internists (MD)",
"Geography Professor",
"Geological Data Technicians",
"Geological Technician (Drafter)",
"Glass Blower",
"Gluing Machine Operators",
"Golf Course Superintendent",
"Government Budget Analyst",
"Government Property Inspectors",
"Government Service Executives",
"Graduate Teaching Assistant",
"Graphic Designer",
"Greenhouse and Nursery Manager",
"Gynecologist (MD)",
"Hand and Portable Tool Mechanic",
"Hand Sewer",
"Harbor Master",
"Harbor, Lake & Waterways Police",
"Hardwood Floor Finisher",
"Hazardous Materials Removal Worker",
"Hazardous Waste Management Analyst",
"Health Care Facilities Inspector",
"Health Case Manager",
"Health Educators",
"Health Psychologist",
"Hearing Officer",
"Heating, A/C, Refrigeration Technician",
"Heavy Equipment Mechanic",
"High School Administrator",
"High School Guidance Counselor",
"High School Teacher",
"Highway Maintenance Worker",
"Highway Patrol Pilot",
"Historic Site Administrator",
"Historical Archivist",
"History Professor",
"Home Appliance Installer",
"Home Appliance Repairer",
"Home Economics Teacher",
"Home Economist",
"Home Entertainment System Installer",
"Home Health Aide",
"Home Health Technician",
"Horticultural Worker Supervisor",
"Horticulture Therapist",
"Horticulturist (Vineyard)",
"Hospital Administrator",
"Hospital Nurse",
"Hosts and Hostesses",
"Hotel and Motel Desk Clerks",
"Hotel Convention/Events Coordinator",
"Hotel Manager",
"Housekeeping Supervisors",
"Human Factors Psychologist",
"Human Resources Management Advisor",
"Human Resources Management Consultant",
"Hydraulic Engineer",
"Immigration Inspector",
"Industrial Air Pollution Analyst",
"Industrial Arts Teacher",
"Industrial Designer",
"Industrial Engineer",
"Industrial Engineering Technician",
"Industrial Health Engineer",
"Industrial Hygienist",
"Industrial Machinery Mechanics",
"Industrial Relations Analyst",
"Industrial Relations Specialist",
"Industrial Therapist",
"Industrial Waste Inspector",
"Industrial-Organizational Psychologist",
"Infantry Officers",
"Instructional Coordinators",
"Instructor, Police-Canine Services",
"Instrument Technician",
"Insulation Installer",
"Insurance Adjuster",
"Insurance Agent",
"Insurance Appraiser (Auto Damage)",
"Insurance Claim Examiner",
"Insurance Claims Adjuster",
"Insurance Claims Clerks",
"Insurance Estate Planner",
"Insurance Lawyer",
"Insurance Policy Processing Clerk",
"Insurance Underwriter",
"Intelligence Specialist (Government)",
"Interior Designer",
"Internal Auditor",
"Interpreter for the Hearing Impaired",
"Irradiated-Fuel Handlers",
"Irrigation Engineer",
"IT Administrator (Information Technology)",
"Janitorial Supervisors",
"Job Analyst",
"Job Development Specialist",
"Job Printer (Graphic Arts)",
"Kindergarten Teacher",
"Labor Relations Advisor",
"Laboratory Tester",
"Land Surveyor",
"Landscape Architect",
"Landscape Contractor",
"Lathe Operator",
"Law Clerks",
"Law Professor",
"Legal Assistant",
"Legal Secretary",
"Legislative Assistant",
"Library Assistant",
"Library Consultant",
"Library Science Professor",
"Library Technician",
"License Clerk",
"Licensed Practical Nurse (LPN)",
"Livestock Commission Agent",
"Loan Counselor",
"Loan Interviewers and Clerks",
"Loan Officer",
"Locomotive Engineers",
"Log Graders and Scalers",
"Logging Tractor Operator",
"Logging Worker Supervisor",
"Machine Feeders and Offbearers",
"Mail Clerk",
"Mail Machine Operators",
"Maintenance Supervisor",
"Makeup Artists - Theatrical",
"Management Consultant (Analyst)",
"Manicurists and Pedicurists",
"Manual Arts Therapist",
"Mapping Technician",
"Marina Boat Charter Administrator",
"Marine and Aquatic Biologist",
"Marine Architect",
"Marine Cargo Surveyor",
"Marine Drafter",
"Marine Engineer",
"Marine Surveyor",
"Marine/Port Engineer",
"Market Research Analyst",
"Marketing Managers",
"Marking Clerk",
"Marriage and Family Therapists",
"Massage Therapist",
"Materials Engineer",
"Materials Inspector",
"Materials Scientist",
"Math Professor",
"Mathematical Technician",
"Meat Packers",
"Meat, Poultry, and Fish Trimmers",
"Mechanical Drafter",
"Mechanical Engineer",
"Mechanical Engineering Technician",
"Mechanical Inspector",
"Medical Administrative Assistant",
"Medical and Public Health Social Workers",
"Medical and Scientific Illustrator",
"Medical Appliance Technician",
"Medical Assistant",
"Medical Equipment Preparer",
"Medical Examiner/Coroner",
"Medical Insurance Claims Analyst",
"Medical Laboratory Technician",
"Medical Photographer",
"Medical Records Administrator",
"Medical Records Technician",
"Medical Secretary",
"Medical Technologist",
"Medical Transcriptionist",
"Mental Health Counselor",
"Mentally Retarded Students Teacher",
"Merchandise Displayer",
"Metal Casting Machine Operator",
"Metal Fabricator",
"Meter Mechanic",
"Middle School Administrator",
"Middle School Guidance Counselor",
"Middle School Teacher",
"Military Analyst",
"Military Officer",
"Military-Enlisted Personnel",
"Mill Worker",
"Mine Cutting Machine Operator",
"Mine Inspector",
"Mining Engineer",
"Mining Machine Operator",
"Mining Shovel Machine Operator",
"Missing Person Investigator",
"Missionary Worker (Foreign Country)",
"Model Maker",
"Model Makers, Metal and Plastic",
"Motion Picture Director",
"Motion Picture Projectionist",
"Motor Vehicle Inspector",
"Motorboat Mechanic",
"Motorcycle Mechanic",
"Municipal Fire Fighting Supervisor",
"Museum Curator",
"Museum Technicians and Conservators",
"Music Arrangers and Orchestrators",
"Music Director",
"Music Teacher",
"Music Therapist",
"Musical Instrument Tuner",
"Narcotics Investigator (Government)",
"New Accounts Clerk (Banking)",
"Newspaper Editor",
"Newspaper/Magazines Writer",
"Non-Retail Sales Supervisor",
"Nuclear Engineer",
"Nuclear Equipment Operation Technician",
"Nuclear Fuels Research Engineer",
"Nuclear Medicine Technologist",
"Nuclear Monitoring Technician",
"Nuclear Power Reactor Operator",
"Nuclear Technicians",
"Numerical Tool Programmer",
"Nurse Practitioner",
"Nurse's Aide",
"Nursery Workers",
"Nursing Professor",
"Obstetrician (MD)",
"Occupational Analyst",
"Occupational Physician (MD)",
"Occupational Safety & Health Inspector",
"Occupational Therapist",
"Occupational Therapy Assistant",
"Oceanographic Assistant",
"Office Clerk",
"Office Machine Mechanic",
"Office Supervisor",
"Offset Press Operators",
"Operating Engineers",
"Operations Management Analyst",
"Ophthalmic Laboratory Technician",
"Ophthalmologist (MD)",
"Oral and Maxillofacial Surgeons",
"Order Clerk",
"Order Fillers, Wholesale and Retail Sales",
"Ordinary Seamen",
"Ornamental-Metalwork Designer",
"Orthodontic Assistant",
"Orthodontic Laboratory Technician",
"Orthodontist (MD)",
"Outdoor Education Teacher",
"Overhead Door Installer",
"Package Designer",
"Packaging Machine Operator",
"Packers and Packagers, Hand",
"Painter (Industrial)",
"Painters, Construction and Maintenance",
"Painters, Transportation Equipment",
"Park Naturalist",
"Parking Enforcement Officer",
"Parking Lot Attendant",
"Parole Officer",
"Parts Salesperson",
"Paste-Up Worker (Graphic Arts)",
"Patent Agent",
"Patent Lawyer",
"Pathologist (MD)",
"Payroll and Timekeeping Clerks",
"PBX Installer and Repairer",
"Peace Corps Worker (Volunteer)",
"Pediatric Dentist",
"Pediatrician (MD)",
"Personal Service Supervisor",
"Personnel Administrator",
"Personnel Assistant",
"Personnel Recruiter",
"Pest Control Workers",
"Pesticide Handlers",
"Petroleum Engineer",
"Petroleum Geologist",
"Petroleum Laboratory Assistant",
"Petroleum Refinery Operator",
"Petroleum Technician",
"Pharmacy Aides",
"Pharmacy Technician",
"Philosophy and Religion Professor",
"Photo-Optics Technician",
"Photoengravers (Graphic Arts)",
"Photogrammetric Engineer",
"Photographic Equipment Mechanic",
"Photographic Process Workers",
"Physical Education Instructor",
"Physical Therapist",
"Physical Therapist Aides",
"Physical Therapy Assistant",
"Physician's Assistant (PA)",
"Physician's Office Nurse",
"Physics Professor",
"Pilot (Commercial Airlines)",
"Plant Breeder",
"Plant Manager (Manufacturing)",
"Plasterers and Stucco Masons",
"Plastic Surgeon",
"Platemakers (Graphic Arts)",
"Plumber (Plumbing Contractor)",
"Poets and Lyricists",
"Police and Detectives Supervisor",
"Police Artist",
"Police Identification and Records Officers",
"Police Officer",
"Political Science Professor",
"Political Scientist",
"Postal Service Clerks",
"Postal Service Mail Carriers",
"Postal Service Mail Sorter",
"Postmasters and Mail Superintendents",
"Power Plant Operators",
"Power-Line Installer and Mechanic",
"Precision Devices Inspectors and Testers",
"Preschool Administrator",
"Preschool Teacher",
"Pressing Machine Operator",
"Pressure Vessel Inspectors",
"Printing/Graphic Arts Reproduction Technician",
"Printmaker (Artist)",
"Private Detectives and Investigators",
"Private Nurse",
"Private Sector Executives",
"Probate Lawyer",
"Probation Officer",
"Procurement Clerks",
"Product Planner",
"Product Safety Engineer",
"Production Planner",
"Production, Planning, and Expediting Clerks",
"Professional Sports Scout",
"Proofreaders and Copy Markers",
"Property Accountant",
"Property Assessor",
"Property Managers",
"Props and Lighting Technicians",
"Prosthetic Technician",
"Psychiatric Aide",
"Psychiatric Technician",
"Psychiatrist (MD)",
"Psychology Professor",
"Public Health Service Officer",
"Public Relations Manager",
"Public Relations Specialist",
"Public Transportation Inspector",
"Publications Editor",
"Purchasing Agent",
"Purchasing Manager",
"Quality Control Coordinator",
"Quality Control Engineer",
"Quality Control Inspector",
"Quality Control Technician",
"Quarry Worker",
"Radar and Sonar Technicians",
"Radiation Protection Engineer",
"Radiation Therapists",
"Radio & TV Announcer",
"Radio & TV News Commentator",
"Radio & TV Newscaster",
"Radio & TV Producer",
"Radio & TV Program Director",
"Radio & TV Sports Announcer",
"Radio & TV Station Administrator",
"Radio & TV Talk Show Host",
"Radio Mechanics",
"Radio Operators",
"Radiologic Technicians",
"Radiologic Technologist",
"Radiologist (MD)",
"Rail Yard Engineers",
"Railroad Conductors and Yardmasters",
"Railroad Engineer",
"Railroad Inspector",
"Range Manager",
"Real Estate Appraiser",
"Real Estate Assessor",
"Real Estate Broker",
"Real Estate Lawyer",
"Real Estate Sales Agents",
"Recreation Leader",
"Recreational Protective Service Worker",
"Recreational Therapist",
"Recreational Vehicle Mechanic",
"Referee / Umpire",
"Refuse and Recyclable Material Collectors",
"Registrar Administrator",
"Reliability Engineer",
"Religious Institution Education Coordinator",
"Reservation Ticket Agent",
"Residence Counselor",
"Resource Recovery Engineer",
"Resource Teacher",
"Respiratory Care Technician",
"Respiratory Therapist",
"Respiratory Therapy Technicians",
"Restaurant Food Coordinator",
"Restaurant Manager",
"Retail Buyer",
"Retail Customer Service Representative",
"Retail Inventory Control Analyst",
"Retail Sales Department Supervisor",
"Retail Salespersons",
"Retail Store Manager",
"Revenue Agent (Government)",
"Safety Inspector",
"Sales Engineers",
"Sales Floor Stock Clerk",
"Sales Managers",
"Sales Promoter",
"Sales Representative (Aircraft)",
"Sales Representative (Chemicals & Drugs)",
"Sales Representative (Computers)",
"Sales Representative (Graphic Arts)",
"Sales Representative (Hotel Furnishings)",
"Sales Representative (Medical Equipment)",
"Sales Representative (Printed Advertising)",
"Sales Representative (Radio & TV Time)",
"Sales Representative (Telecommunications)",
"Sales Representative (Teleconferencing)",
"Sales Representative ( Education Programs)",
"Sales Representatives (Agricultural Products)",
"Sales Representatives (Instruments)",
"Sales Representatives (Mechanical Equipment)",
"Sales Representitive (Psychological Tests)",
"Sanitary Engineer",
"Sawing Machine Operator",
"Scanner Operators",
"School Nurse",
"School Plant Consultant",
"School Psychologist",
"Scientific Linguist",
"Scientific Photographer",
"Screen Printing Machine Operators",
"Screen Writer",
"Script Editor",
"Securities Broker",
"Security and Fire Alarm Systems Installers",
"Security Guard",
"Self-Enrichment Education Teachers",
"Septic Tank and Sewer Servicers",
"Service Station Attendants",
"Set Designer",
"Set Illustrator",
"Sewing Machine Operators",
"Sheet Metal Workers",
"Ship Carpenters and Joiners",
"Ship Engineers",
"Ship Master",
"Ship Mate",
"Ship Pilot",
"Shipping, Receiving, and Traffic Clerks",
"Shoe Machine Operators",
"Signal Switch Repairers",
"Skin Care Specialists",
"Small Engine Mechanics",
"Social and Community Service Managers",
"Social and Human Service Assistants",
"Social Psychologist",
"Social Science Research Assistants",
"Social Service Volunteer",
"Social Welfare Administrator",
"Social Work Professor",
"Social Worker",
"Sociology Professor",
"Soil Conservation Technician",
"Soil Conservationist",
"Soil Engineer",
"Soil Scientist",
"Solar Energy Systems Designer",
"Solid Waste Disposal Administrator",
"Sound Engineering Technicians",
"Special Education Administrator",
"Special Forces",
"Special Forces Officers",
"Speech Pathologist",
"Speech Writer",
"Sport Psychologist",
"Sport's/Entertainment Agent (Manager)",
"Sports Agent",
"Sports Events Business Manager",
"Sports Physician (Orthopedist)",
"Sportswriter (Journalist)",
"Stained Glass Artist",
"Standards Engineer",
"Statement Clerks",
"Stationary Engineers",
"Statistical Assistants",
"Steel Workers",
"Storage and Distribution Manager",
"Stress Analyst Engineer",
"Structural Drafter",
"Structural Engineer",
"Student Admissions Administrator",
"Student Affairs Administrator",
"Student Financial Aid Administrator",
"Substance Abuse Counselor",
"Subway and Streetcar Conductor",
"Surgeons (MD)",
"Surgical Technician/Technologist",
"Survey Researchers",
"Surveying Technicians",
"Switchboard Operator",
"Systems Accountant",
"Systems Analyst, Data Processing",
"Tax Accountant",
"Tax Auditor",
"Tax Collector",
"Tax Examiner",
"Tax Lawyer",
"Tax Preparer",
"Taxi Drivers and Chauffeurs",
"Teacher of the Blind",
"Teachers Aide",
"Team Assemblers",
"Technical & Scientific Publications Editor",
"Technical Directors/Managers",
"Technical Illustrator",
"Technical Publications Writer",
"Technological Espionage Intelligence Agent",
"Telecommunications Line Installers and Repairers",
"Telecommunications Maintenance Worker",
"Telecommunications Technician",
"Telephone Station Installers",
"Textile Bleaching and Dyeing Machine Operators",
"Textile Cutting Machine Operators",
"Textile Designer",
"Tile and Marble Setters",
"Title Examiner",
"Title Searchers",
"Tool & Machine Designer",
"Tool and Die Makers",
"Tool Grinders, Filers, and Sharpeners",
"Tour Guide",
"Town Clerk",
"Traffic Administrator (Freight & Passenger)",
"Traffic Agent",
"Traffic Technicians",
"Transit and Railroad Police",
"Transportation Attendants",
"Transportation Systems Design Engineer",
"Travel Agent",
"Travel Clerks",
"Travel Counselor",
"Travel Writer (Journalist)",
"Treasurer (Corporate)",
"Treatment Plant Operators",
"Tree Trimmers and Pruners",
"Truck Driver, Light Duty",
"Truck Driver, Long Distance",
"Ultrasound Technologist",
"Unemployment Inspector",
"Urban and Regional Planner",
"Ushers and Lobby Attendants",
"Utility Meter Reader",
"Vending Machine Mechanic",
"Veterinarian (VMD)",
"Veterinarian Technician",
"Veterinary Assistant",
"Video Engineer",
"Vocational Education Instructors College",
"Vocational Education Teachers, High School",
"Vocational Education Teachers, Middle School",
"Vocational Rehabilitation Counselor",
"Voice Pathologist",
"Waiters and Waitresses",
"Warehouse Stock Clerk",
"Watch Repairers",
"Water Pollution Control Inspector",
"Weather Observer",
"Web Art Director",
"Weighers and Measurers",
"Welder (Gas, Arc, Plasma, Laser)",
"Welfare Eligibility Workers and Interviewers",
"Wholesale Buyers",
"Wildlife Biologist",
"Wildlife Control Agent",
"Windows - Draperies Treatment Specialist",
"Woodworking Machine Operators",
"Word Processing Specialist",
"Writer /Author",
"Zoo Veterinarian",
"Zoologis"];


var nationalities = ['American', 'Canadian', 'Arabian', 'Russian', 'German', 'British', 'French', 'Chineese', 'Indian', 'Mexican', 'Brazillian', 'Philipino'];
var religions = ['Islam', 'Christianity', 'Atheism', 'Judaism', 'hinduism', 'Buddhism'];

function limitedRandom(min, max){
	return Math.floor(Math.random() * (max - min) + min);
}

var people = [];
for(var i=0;i<1000;i++){
	people.push({
		title: 'Mrs.',
		first_name: female_names[i],
		middle_name: female_names[999 - i],
		last_name: last_names[i],
		gender: 'female',
		birthday: new Date(limitedRandom(12,1) + "-" + limitedRandom(1,30) + "-" + limitedRandom(1940,1995)),
		occupation: occupations[limitedRandom(0,950)],
		father_name: male_names[limitedRandom(0,999)],
		mother_name: female_names[limitedRandom(0,999)],
		nationality: nationalities[limitedRandom(0,12)],
		religion: religions[limitedRandom(0,6)]
	});
}

for(var i=0;i<1000;i++){
	people.push({
		title: 'Mr.',
		first_name: male_names[i],
		middle_name: male_names[999 - i],
		last_name: last_names[i],
		gender: 'male',
		birthday: new Date(limitedRandom(12,1) + "-" + limitedRandom(1,30) + "-" + limitedRandom(1940,1995)),
		occupation: occupations[limitedRandom(0,950)],
		father_name: male_names[limitedRandom(0,999)],
		mother_name: female_names[limitedRandom(0,999)],
		nationality: nationalities[limitedRandom(0,12)],
		religion: religions[limitedRandom(0,6)]
	});
}

module.exports = people;